FROM node:23-alpine

USER node
WORKDIR /app

COPY --chown=node:node package*.json ./
RUN npm ci --only=production

COPY --chown=node:node . .

EXPOSE 3003
ENV NODE_ENV=production

CMD ["npm", "start"]