POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "abe49c01-ca90-4968-87e7-81723e4c837b"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "3392a646-d26b-4d9b-b9b7-b7c3e5901c7a",
    "account_id_to": "e8384256-fba8-42f6-9643-3e22fea4f088",
    "amount": 30
}